(function () {
    'use strict';
    angular.module("BlurAdmin.pages.service",
        [
            "BlurAdmin.domain.domainService",
            'BlurAdmin.dimension.dimensionService',
            'BlurAdmin.interface.interfaceService',
            'BlurAdmin.field.fieldService',
            'BlurAdmin.interfacemodel.interfaceModelService',
            'BlurAdmin.limitword.limitwordService',
            'BlurAdmin.settingTemplet.settingTempletService',
            'BlurAdmin.limitword.limitwordService'
        ])
        .config(routeConfig);

    function routeConfig($stateProvider) {
        $stateProvider.state("service",{
            url:'/service',
            template:"<ui-view autoscroll='true' autoscroll-body-top></ui-view>",
            abstract:true,
            title:'服务管理',
            controller:'mainCtrl',
            sidebarMeta:{
                icon:"ion-gear-b",
                order:40
            }
        }).state("service.interface",{
            url:'/service.interface',
            templateUrl:'app/pages/service/interface/serviceInterface.html',
            title:"接口",
            sidebarMeta:{
                order:0
            }
        })/*.state("service.report",{
            url:'/serviceReport',
            templateUrl:'app/pages/service/report/serviceReport.html',
            title:"报告",
            sidebarMeta:{
                order:10
            }
        }).state("service.monitor",{
            url:'/serviceMonitor',
            templateUrl:'app/pages/service/monitor/serviceMonitor.html',
            title:"监控",
            sidebarMeta:{
                order:20
            }
        }).state("service.test",{
            url:'/serviceTest',
            templateUrl:'app/pages/service/test/serviceTest.html',
            title:"测试",
            sidebarMeta:{
                order:30
            }
        }).state("service.systemMonitor",{
            url:'/systemMonitor',
            templateUrl:'app/pages/service/systemMonitor/systemMonitor.html',
            title:"系统",
            sidebarMeta:{
                order:40
            }
        })*/.state("service.domain",{
            url:'/serviceDomain',
            templateUrl:'app/pages/service/domain/serviceDomain.html',
            title:"领域",
            sidebarMeta:{
                order:50
            }
        }).state("service.dimension",{
            url:'/serviceDimension',
            templateUrl:'app/pages/service/dimension/serviceDimension.html',
            title:"维度",
            sidebarMeta:{
                order:60
            }
        }).state("service.interfaceModel",{
            url:'/serviceInterfaceModel',
            templateUrl:'app/pages/service/interfaceModel/serviceInterfaceModel.html',
            title:"模型",
            sidebarMeta:{
                order:70
            }
        }).state("service.report",{
            url:'/serviceReport',
            templateUrl:'app/pages/service/report/serviceReport.html',
            title:"报告",
            sidebarMeta:{
                order:71
            }
        }).state("service.limitword",{
            url:'/serviceLimitword',
            templateUrl:'app/pages/service/limitword/limitwordList.html',
            title:"限定词",
            sidebarMeta:{
                order:80
            }
        }).state("service.settingTemplet",{
            url:'/serviceSettingTemplet',
            templateUrl:'app/pages/service/settingTemplet/settingTempletList.html',
            title:"配置模板",
            sidebarMeta:{
                order:90
            }
        }).state("service.blackIpList",{
            url:'/serviceBlackIpList',
            templateUrl:'app/pages/service/',
            title:"IP黑名单",
            sidebarMeta:{
                order:100
            }
        }).state("service.detail",{
            url:'/serviceInterfaceDetail',
            templateUrl:'app/pages/service/interface/serviceInterfaceDetail.html',
            title:"查看"
        }).state("service.interfaceUpdate",{
            url:'/serviceInterfaceUpdate',
            templateUrl:'app/pages/service/interface/serviceInterfaceUpdate.html',
            title:"修改接口"
        }).state("service.interfaceAddPage",{
            url:'/serviceInterfaceAddPage',
            templateUrl:'app/pages/service/interface/serviceInterfaceAddPage.html',
            title:"新增接口"
        }).state("service.dimensionAddPage",{
            url:'/serviceDimensionAddPage',
            templateUrl:'app/pages/service/dimension/newDimension.html',
            title:"新增维度"
        }).state("service.domainAddPage",{
            url:'/serviceDomainAddPage',
            templateUrl:'app/pages/service/domain/newDomain.html',
            title:"新增领域"
        }).state("service.domainEdit",{
            url:'/serviceDomainEdit',
            templateUrl:'app/pages/service/domain/editDomain.html',
            title:"编辑领域"
        }).state("service.dimensionEdit",{
            url:'/serviceDimensionEdit',
            templateUrl:'app/pages/service/dimension/editDimension.html',
            title:"修改维度"
        }).state("service.interfaceModelAddPage",{
            url:'/serviceInterfaceModelAddPage',
            templateUrl:'app/pages/service/interfaceModel/addInterfaceModel.html',
            title:"新增模型"
        }).state("service.interfaceModelEditPage",{
            url:'/serviceInterfaceModelEditPage',
            templateUrl:'app/pages/service/interfaceModel/editInterfaceModel.html',
            title:"修改模型"
        }).state("service.limitwordAddPage",{
            url:'/serviceLimitwordAddPage',
            templateUrl:'app/pages/service/limitword/newLimitword.html',
            title:"新增限定词"
        }).state("service.settingTempletAddPage",{
            url:'/serviceSettingTempletAddPage',
            templateUrl:'app/pages/service/settingTemplet/addSettingTemplet.html',
            title:"新增模板"
        }).state("service.settingTempletEditPage",{
            url:'/serviceSettingTempletEditPage',
            templateUrl:'app/pages/service/settingTemplet/editSettingTemplet.html',
            title:"编辑模板"
        }).state("service.addReport",{
            url:'/addReport',
            controller:'addReportCtrl',
            templateUrl:'app/pages/service/report/addReport.html',
            title:"新增报告"
        }).state("service.updateReport",{
            url:'/updateReport',
            params:{items:null},
            controller:'updateReportCtrl',
            templateUrl:'app/pages/service/report/updateReport.html',
            title:"修改报告"
        })
    }

})();